### ISSUE TITLE
viewing settings for @example.com gives a blank page.

### ISSUE THREAD

**Issue by jstr33t** [technion/maia_mailguard#29] opened 2015-05-04 16:17 UTC
Hello, I am testing `Maia 1.0.4` on `Ubuntu 12.04.5` and seeing a possible bug

What is happening:

1. log in as my account which is super user
2. click the `admin` key icon
3. select `domains`
4. select the domain `@example.com`
5. verify you are "Default User for Domain @example.com"
6. click `settings`

You get a blank page and in apache logs you see the error:

    PHP Fatal error:  Call to undefined method MDB2_Error::execute() in /var/www/maia/settings.php on line 296, referer: http://mail.example.com/maia/welcome.php

What happens on `Maia 1.0.2c`

1. log in as my account which is super user
2. click the `admin` key icon
3. select `domains`
4. select the domain `@example.com`
5. verify you are "Default User for Domain @example.com"
6. click `settings`

You get the settings for my user.

**Comment by technion** [comment] 2015-05-05 00:20
I'm unable to replicate this in my installation, so I'll need to spend some time investigating all the code paths and determining what may be different in yours.

I will be doing that however, I'm about to leave the country for a few weeks and access to Github will be limited. No less than a dozen people promised to contribute to this project if I brought it back to life - it'd be appreciated if someone could investigate this in my absence.

**Comment by jstr33t** [comment] 2015-05-05 08:22
@technion is there any more information about my system that would help?

Also poke people on the mailing list about github ;)

Enjoy the trip.

**Comment by technion** [comment] 2015-07-13 23:54
Just following up on this. I've still had no luck replicating. Can you get any logs from Apache? "Whitescreen" type errors have historically been a 500 error, which logs as such in the error log.

**Comment by jstr33t** [comment] 2015-07-14 11:13
hi @technion.   Just the same log entry as listed above

    [Tue Jul 14 09:32:06 2015] [error] [client 10.7.7.126] PHP Fatal error:  Call to undefined method MDB2_Error::execute() in /var/www/maia/settings.php on line 296, referer: http://mail.example.com/maia/welcome.php


It's only for the domain entry @example.com  all defined users work as expected

Line 296 for me (and the following lines)

        $res = $sth->execute(array($domain_id));
        if ($row = $res->fetchrow()) {
            $smarty->assign('enable_user_autocreation', $row["enable_user_autocreation"]);
            $smarty->assign('routing_domain', $row["routing_domain"]);
            $smarty->assign('transport', $row["transport"]);
        }

**Comment by technion** [comment] 2015-07-14 11:22
I'm struggling to find the issue. Would you mind adding this between 295 and 296?

        if (PEAR::isError($sth)) { 
             die($sth->getMessage()); 
         } 

It's the error trapping code we've use everywhere else, but for some reason that section doesn't have it. It might help you get a better error output.

**Comment by jstr33t** [comment] 2015-07-15 08:16
Done, so it appears as the following in code:

        if (PEAR::isError($sth)) {
                die($sth->getMessage());
        }
        $res = $sth->execute(array($domain_id));
        if ($row = $res->fetchrow()) {
            $smarty->assign('enable_user_autocreation', $row["enable_user_autocreation"]);
            $smarty->assign('routing_domain', $row["routing_domain"]);
            $smarty->assign('transport', $row["transport"]);
        }


No error in apache logs, but in browser I get: `MDB2 Error: no such field`

**Comment by technion** [comment] 2015-07-15 08:51
>no such field

This is why my massive blast of error logging was useful - it's just a shame I didn't get every single statement. But at least now, you've got an error that makes sense, and it's in the browser where it's *really* obvious.

Can you try a generic SQL query from the MySQL console?

    SELECT enable_user_autocreation, routing_domain, transport 
    FROM maia_domains  
    WHERE maia_domains.id = 1

I have a feeling your database is broken in some way. Was this database migrated from your earlier maia instance?

**Comment by technion** [comment] 2015-07-15 09:02
Update: There's probably more to be gained by running this from your MySQL CLI:

    DESCRIBE maia_domains

**Comment by jstr33t** [comment] 2015-07-15 11:15
For the first statement

    ERROR 1054 (42S22): Unknown column 'routing_domain' in 'field list'


For `DESCRIBE maia_domains`

    +--------------------------+------------------+------+-----+------------+----------------+
    | Field                    | Type             | Null | Key | Default    | Extra          |
    +--------------------------+------------------+------+-----+------------+----------------+
    | id                       | int(10) unsigned | NO   | PRI | NULL       | auto_increment |
    | domain                   | varchar(255)     | NO   | UNI | NULL       |                |
    | reminders                | char(1)          | NO   |     | N          |                |
    | charts                   | char(1)          | NO   |     | N          |                |
    | enable_user_autocreation | char(1)          | NO   |     | Y          |                |
    | language                 | varchar(10)      | NO   |     | en         |                |
    | charset                  | varchar(20)      | NO   |     | ISO-8859-1 |                |
    +--------------------------+------------------+------+-----+------------+----------------+


> Was this database migrated from your earlier maia instance?

yes, from 1.0.2.

**Comment by technion** [comment] 2015-07-15 22:55
If you head on over to [the database creation script](https://github.com/technion/maia_mailguard/blob/master/maia-mysql.sql) you can see there are two extra fields:

    routing_domain               varchar(255) DEFAULT '' NOT NULL, 
    transport                    varchar(255) DEFAULT ':' NOT NULL, 

I would have documented the upgrade path - but these fields existed in the original codebase at the time I forked it.

If you can add these fields to the table from the MySQL CLI I'm expecting this will resolve it.

**Comment by technion** [comment] 2015-07-22 01:49
I'm fairly confident that the issue is identified so I'll close this ticket. Contact me if further assistance is required.

**Closed by technion** 2015-07-22 01:49 UTC

**Comment by jstr33t** [comment] 2016-05-13 10:03
technion sorry what is the best way to add these two fields to the db?

**Comment by technion** [comment] 2016-05-13 10:49
I don't have any installation this broken to not have these fields, and I don't want to paste an answer here and risk it being incorrect.

    add these fields to the table from the MySQL CLI

I would recommend reviewing appropriate MySQL documentation.
